name: API Tests

on:
  push:
    branches:
      - main  # Trigger action on push to main branch
  pull_request:
    branches:
      - main  # Trigger action on pull requests to main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pytest requests  # Install required dependencies

    - name: Start FastAPI server
      run: |
        nohup python apiserver.py &  # Run FastAPI server in the background
      env:
        PYTHONUNBUFFERED: 1  # Ensure logs are displayed in real-time

    - name: Wait for server to be ready
      run: sleep 5  # Wait 5 seconds for the server to be up

    - name: Run tests
      run: pytest testAutomationPytest.py  # Run the tests with pytest

